=== Configured User

The most common way to interact with a SAP system in enterprise applications is to use a central SAP user that is shared by all users of the application.
Using this kind of authentication is a matter of configuration.
When using Hibersap with JCo, the user credentials are provided through Hibersap configuration, namely the JCo properties defined for a `SessionManager`.
When using Hibersap with JCA, the credentials are usually defined in the resource adapter configuration.


=== Per-session authentication

If the application has to provide user credentials, e.g. when each application user logs on to the SAP system using his own SAP account, you can specify logon credentials for each Hibersap session you create.

In this case, when obtaining a `Session` from the `SessionManager`, the method `openSession( org.hibersap.session.Credentials )` must be used. The authentication information is specified in the `Credentials` object.

[source,java]
----
Credentials credentials = new Credentials()
    .setUser("archibald_tuttle")
    .setPassword("myPassw0rd")
    .setLanguage("EN");
Session session = sessionManager.openSession( credentials );
session.execute( bapiClass );
...
----

Hibersap simply passes the attributes defined in the credentials object to SAP.
The following table lists the available attributes of the `Credentials` class including the corresponding JCo parameter as defined in interface `com.sap.conn.jco.ext.DestinationDataProvider` of the SAP Java Connector version 3.

[options="header"]
|===
| Credentials field | Description                                                       | JCo parameter
| `user`            | SAP logon user                                                    | `jco.client.user`
| `aliasUser`       | SAP logon user alias, can be used instead of logon user           | `jco.client.alias_user`
| `client`          | SAP client                                                        | `jco.client.client`
| `language`        | Logon language ISO code                                           | `jco.client.lang`
| `password`        | Logon password                                                    | `jco.client.passwd`
| `ssoTicket`       | SAP Cookie Version 2 as logon ticket for SSO based authentication | `jco.client.mysapsso2`
| `x509Certificate` | X509 certificate for certificate based authentication             | `jco.client.x509cert`
|===

Using this method with JCo mode, Hibersap will internally create a custom JCo destination setting the specified credential attributes.
Note that in this case, every user needs to have the proper permissions in SAP to use the function modules that are called via Hibersap.

In addition to calling the function modules itself, JCo makes calls to the SAP system to obtain meta data on function modules, the so-called repository calls.
Those calls depend on different sets of permissions which the specific user might or might not have.
Therefore, JCo uses a configured user to do repository calls instead of the current user supplied with the Hibersap credentials object when creating custom destinations.
This user may either be configured via the JCo parameter `jco.client.user`, or with a separate user for repository calls using the parameter `jco.destination.repository.user`.
The latter is recommended for applications which make use of per-session authentication, for this makes sure the functions are always called with the session user and the repository calls are done with the repository user.
In this case, the property `jco.client.user` should not be set.

When using Hibersap with JCA, the configuration should be done accordingly, but is resource adapter specific.
The Cuckoo Resource Adapter defines almost all possible JCo properties and passes them on to the Java Connector.


=== Single sign-on

A special case of per-session authentication is the use of single sign-on.
In a SAP environment it is common to use SAP Logon Tickets issued by SAP systems.
In a web application / portal scenario the ticket is stored in a cookie named `MYSAPSSO2` in the HTTP user session.
After obtaining this ticket it can be passed to the Hibersap session by setting the `Credentials.ssoTicket' field object like described in the previous section.


