=== The Hibersap libraries

The Hibersap framework is divided into the following libraries:

* hibersap-core
* hibersap-jco
* hibersap-jca
* hibersap-ejb

When using Hibersap in conjunction with a JCA compatible resource adapter, both the hibersap-core and the hibersap-jca jars must be on the application's classpath.
When using Hibersap with the SAP Java Connector (JCo), the hibersap-core and the hibersap-jco libraries are needed.

When using Hibersap with EJBs, you may consider using the EJB tools provided by the hibersap-ejb library.
The EJB tools provide an EJB3 interceptor which takes care of opening and closing sessions as well as injecting them into your EJBs at a special injection point denoted by a @HibersapSession annotation.
See section link:#hibersap-ejb-tools[Hibersap EJB Tools] for more information.

=== Third Party Libraries

Hibersap has a few dependencies on third-party libraries, which you need to add to your application's classpath. The easiest way to achieve this is to build your projects with Maven.
See section link:#building-hibersap-applications-with-maven[Building Hibersap Applications with Maven].

Depending on which interfacing technology is actually used, you also need the SAP Java Connector (JCo)
or a JCA compatible resource adapter.

==== Hibersap Dependencies

When using Maven, it will download the dependencies automatically during the build.
Otherwise, you need to add dependencies manually.
The following sections show Hibersap's runtime dependencies and their version as Maven coordinates, so they can easily be downloaded from the Maven central repository.

===== hibersap-core Dependencies

* Apache Commons Lang: commons-lang:commons-lang:2.6
* Apache Commons Logging: commons-logging:commons-logging:1.2

===== hibersap-jco Dependencies

* hibersap-core dependencies, plus:
* SAP Java Connector (JCo) version 3.0.x (see section link:#the-sap-java-connector-jco[The SAP Java Connector (JCo)])

===== hibersap-jca Dependencies

* hibersap-core dependencies, plus:
* Java EE Connector Architecture API: javax.resource:connector:1.0 (or higher)

===== hibersap-ejb Dependencies

* Java Enterprise Java Beans API: javax.ejb:ejb-api:3.0 (or higher)


==== The SAP Java Connector (JCo)

The SAP JCo library is provided by SAP to their customers and comes with its own (commercial) license.
Thus it can not be provided by public Maven repositories or download sites.
Please check the following URL for more information and downloads: {url-sapjco-download}.
You need to have an account for this URL, which may be obtained by SAP customers.
Valuable help regarding SAP technologies can also be found on the SAP Community Network (SCN): {url-sap-community-network}.

After downloading SAP Java Connector 3.0, extract the sapjco3.jar and the sapjco3 native library.
You then need to install the sapjco3.jar into your local Maven repository or deploy it to your project's or company's remote repository.

To install it to your local Maven repository issue the following Maven command on the command line.
Since JCo is defined as an optional dependency in Hibersap, you can choose any values for groupId, artifactId and version.
You make sure your project's pom.xml defines the dependency with the matching coordinates.

Note: The artifactId `com.sap.conn.jco.sapjco3` is a trick to work around a runtime check in the latest versions of
the SAP JCo library which enforces the name of the loaded jar file to either equal "sapjco3.jar" (or to start with
"com.sap.conn.jco").
Without this, Maven would rename the jar file to something like "sapjco3.jar-{sapjco-version}.jar" when copying it
from the repository which would lead to runtime errors.

[subs="+attributes"]
----
mvn install:install-file -DgroupId=org.hibersap \\
                         -DartifactId=com.sap.conn.jco.sapjco3 \\
                         -Dversion={sapjco-version} \\
                         -Dpackaging=jar -Dfile=sapjco.jar
----

The native library must be on your application's library path.
You may copy it to a global library path, to a special directory such as `C:/WINDOWS/SYSTEM32` on Windows systems or to the execution directory of the application (e.g. the bin folder of your application server or the folder from which you run your application).
Additionally, the JCo jar file must be on the application's classpath.

You may set the Java library path programmatically within your application by calling

[source,java]
----
System.setProperty("java.library.path", "/the/actual/path/to/sapjco3-native-lib/");
----

or by passing it to the Java runtime when executing your Java application using

----
java [...] -Djava.library.path="/the/actual/path/to/sapjco3-native-lib/"
----


=== The Cuckoo Resource Adapter for SAP

If you are using Hibersap with a resource adapter in a managed environment, the preferred choice is the Cuckoo Resource Adapter for SAP.
The project's web site can be found under {url-cuckoo-ra}.

You need to deploy the resource adapter to your application server. Since it uses the SAP Java Connector internally, the previous section also applies to this scenario, i.e. the SAP JCo has to be installed for use within the application server.


=== Other JCA compatible Resource Adapters

Being the only open source resource adapters for SAP, Hibersap was tested with Cuckoo as well as the SAP BAPI JCA Adapter (see {url-sapbapijcaadapt}).
Nevertheless, commercial alternatives do exist. We would be glad to get your feedback when using one of these.
Note that a resource adapter must implement the JCA Common Client Interface (CCI) to be supported by Hibersap.

Integrating another Resource Adapter in combination with application-managed authentication includes writing a Resource Adapter specific implementation of the interface `org.hibersap.execution.jca.cci.ConnectionSpecFactory`.
This is due to a limitation in the JCA specification which specifies the `javax.resource.cci.ConnectionSpec` as an empty interface, letting it up to the vendor-specific implementation to define which properties it contains.
Hibersap's aim to support different resource adapters means that there must be a layer on top of the ConnectionSpec interface which makes it possible to adapt to different JCA implementations without having explicit dependencies to each of them.
Hibersap implements ConnectionSpecFactories for Cuckoo as well as the SAP BAPI JCA Adapter that use reflection for setting and getting the ConnectionSpec's parameters in order to reduce (compile-time) dependencies to the individual resource adapters.

However, an implementation of the `ConnectionSpecFactory` is not needed if the application uses only container-managed authentication, because in this case Hibersap does not need to use a ConnectionSpec.


=== Building Hibersap Applications with Maven

The Hibersap libraries are deployed to the Maven Central repository, so the dependencies are downloaded by Maven when you specify them in your project.

The following listing shows how to specify the dependencies to the Hibersap libraries in your pom.xml.

If you use Hibersap directly with JCo you need to declare the following dependencies in your project:

[source,xml,subs="+attributes"]
----
<dependency>
    <groupId>org.hibersap</groupId>
    <artifactId>hibersap-core</artifactId>
    <version>{hibersap-version}</version>
    <type>jar</type>
</dependency>
<dependency>
    <groupId>org.hibersap</groupId>
    <artifactId>hibersap-jco</artifactId>
    <version>{hibersap-version}</version>
    <type>jar</type>
</dependency>
<dependency>
    <groupId>org.hibersap</groupId>
    <artifactId>com.sap.conn.jco.sapjco3</artifactId>
    <version>{sapjco-version}</version>
    <type>jar</type>
</dependency>
----

When using Hibersap with JCA you need to declare the following dependencies:

[source,xml,subs="+attributes"]
----
<dependency>
    <groupId>org.hibersap</groupId>
    <artifactId>hibersap-core</artifactId>
    <version>{hibersap-version}</version>
    <type>jar</type>
</dependency>
<dependency>
    <groupId>org.hibersap</groupId>
    <artifactId>hibersap-jca</artifactId>
    <version>{hibersap-version}</version>
    <type>jar</type>
</dependency>
----

Due to Maven's dependency management capabilities, all transient dependencies are automatically resolved so that there is no need to specify any of the above mentioned third-party libraries.
One exception to this is the dependency to the SAP Java Connector (JCo) which you need when using Hibersap directly with JCo. This dependency in declared as __optional__ in the pom.xml of the hibersap-jco module. Because of this it is explicitly declared in the above example.
