
When developing applications which run inside a Java EE application server and make use of Enterprise Java Beans (EJB), it is
recommended using Hibersap in combination with a JCA compatible resource adapter. A resource adapter offers some important features which will be treated in this section.


=== Transaction Management

In an application server the JTA transaction manager handles transactions.
In combination with EJBs and container managed transactions (CMT), the application code does not need to care about transaction demarcation because the container sets the transaction boundaries implicitly. This simplifies development and reduces the probability of errors.

If using CMT, all the function calls to SAP which take place during a call to an EJB business method are running in one transaction.
When the EJB method returns normally, the transaction manager commits the transaction while in case of an error the transaction is automatically rolled back.
In this context, error means that either a `RuntimeException` is thrown or a Java EE application exception configured with the `rollback=true` attribute. (Note that Hibersap itself only throws unchecked exceptions.)

In EJB3, container managed transaction is the default transaction management demarcation.
However, can be explicitly declared using the `@TransactionManagement` annotation with a transaction management type of `CONTAINER` or `BEAN`.
The transaction semantics are further defined by the `@TransactionAttribute` annotation on the EJB class or the individual EJB methods where `TransactionAttributeType.REQUIRED` is a sensible default value.


==== Distributed Transactions

In an application it might be necessary or wanted to access SAP and other resources like a database and/or a JMS message queue in one unit of work making sure either every resource is committed in the case of success, or every resource is rolled back in case of an error. To accomplish this, Java EE supports distributed transactions through the JTA transaction manager.

Unfortunately, SAP R/3 does not provide the two-phase commit protocol (2PC) which is necessary for a resource to participate in a distributed transaction.
The effect is that resource adapters for SAP R/3 support only local transactions, which is no problem if there is only one resource (the SAP R/3 system) enlisting in a transaction.
If there are multiple resources participating in a distributed transaction, the transaction manager starts a distributed transaction which requires 2PC aware resources as its participants.

The good news is that almost all of the modern application servers (including JBoss/Wildfly, Glassfish, Bea Weblogic and SAP WebAS) support a strategy called Last Resource Commit Optimization which makes it possible for a single non-2PC-aware resource (in our case SAP) to enlist in a distributed transaction.
This is transparent for the programmer.
However, as soon as there are two non-2PC-resources enlisting in the distributed transaction, the transaction manager will throw an error.

// TODO code examples


=== Security Management

With a resource adapter there are two different methods to authenticate with the SAP R/3 system: container managed and component managed authentication.
Hibersap supports both authentication methods.

With component managed authentication, an application passes credentials each time a connection is obtained from the resource adapter.
This method may be used when each user of the application signs in using its own SAP user, e.g. by entering the user name and password in the application or when using single sign-on with logon tickets.
In JCA, the credentials are passed with a `javax.resource.cci.ConnectionSpec` instance.
Internally, Hibersap will create this instance and fill it with information passed with the credentials object when a new session is opened. (The code is the same as in link:#per-session-authentication[Per-session authentication].)

[source,java]
----
Credentials credentials = new Credentials()
    .setUser("archibald_tuttle")
    .setPassword("myPassw0rd");
Session session = sessionManager.openSession( credentials );
session.execute( bapiClass );
[...]
----

With container managed authentication the sing-on information is either obtained from a JAAS login module or -- in the simplest case -- a central user and password is taken from the resource adapter's configuration.
Using a login module, the sign-on information is passed by the container to the resource adapter with a `javax.security.auth.Security` object. Login module configuration is container specific.


=== JCA Configuration

Another advantage of using a resource adapter over using JCo directly is that a resource adapter can be deployed and configured independently of the applications that use it.
Thus it is not necessary to reconfigure and redeploy all applications that connect to a SAP system whenever connection parameters (e.g. the SAP system's host name) change.
Instead, only the resource adapter has to be reconfigured.
Since the configuration of the resource adapter specifies all the necessary properties to access the SAP system, in the Hibersap configuration you just need to specify the JNDI name that is used to look up the resource adapter's connection factory.


=== Hibersap EJB tools

If using Hibersap in a Java EE environment with Enterprise Java Beans, consider using the Hibersap EJB tools.
The EJB tools help in automatically creating Hibersap Sessions, injecting them into your EJBs and closing them.

The following code implements a Stateless Session EJB with a business method to search for Customers in SAP.
The EJB's business methods are intercepted with the `HibersapSessionInterceptor`.
It has a field named `session` which is annotated with `@HibersapSession` to tell the interceptor which `SessionManager` to inject into the EJB.
The annotation's `value` parameter specifies a JNDI name to which the `SessionManager` is bound.

[source,java]
----
@Stateless
@Interceptors( HibersapSessionInterceptor.class )
public class CustomerServiceBean implements CustomerService
{
    @HibersapSession( "java:global/eis/hibersap/A12" )
    private Session session;

    public CustomerSearch search( String nameSearchPattern )
    {
        CustomerSearch customerSearch = new CustomerSearch( nameSearchPattern );
        session.execute( customerSearch );
        return customerSearch;
    }
}
----

`CustomerSearch` is a Hibersap BAPI class. As can be seen, the code can directly use the injected Hibersap session to call functions in the SAP backend.
There is no need to close the Session, this is done by the interceptor.
The example uses container managed transactions and the method is called with transaction attribute `REQUIRED` (the default behaviour).
This makes sure the SAP call is transactional and will be committed or rolled back by the transaction manager after the EJB business method was executed.

Internally, the interceptor adds each created Hibersap session to the EJB's session context to make sure that subsequent calls to other EJBs use the same session.
When the HibersapSessionInterceptor is executed, it first checks if a session of the specified session manager is already in the session context. If so, it uses the existing session, else a new session is created.

On returning from the business method for which the session was opened, the interceptor will close the session, thus making sure the underlying JCA connection will be returned to the connection pool.

To make the example complete we need a way to create a `SessionManager` and bind it to JNDI where it can be looked up by the interceptor.
The following code implements a singleton EJB with the `@Startup` annotation that is created when the application gets deployed.
The container will automatically call the lifecycle method `rebindSessionManager()` which is annotated with `@PostConstruct` when the EJB is started.
The method creates a session manager from a Hibersap XML configuration file and binds it to JNDI. When the application gets undeployed, the method `unbindSessionManager()` is called which removes the session manager from JNDI.
To actually bind and unbind the session manager to and from JNDI, the helper methods in class `JndiUtil` are used which is a part of the hibersap-ejb module.

[source,java]
----
@Singleton
@Startup
public class HibersapBootstrapBean
{
    // The JNDI name we will bind the Hibersap SessionManager to
    // (not the name of the JCA connection factory!)
    public static final String JNDI_NAME = "java:jboss/eis/hibersap/SM_A12";

    @PostConstruct
    public void rebindSessionManager()
    {
        SessionManager sessionManager = new AnnotationConfiguration("A12").buildSessionManager();
        JndiUtil.rebindSessionManager( sessionManager, JNDI_NAME );
    }

    @PreDestroy
    public void unbindSessionManager()
    {
        JndiUtil.unbindSessionManager( JNDI_NAME )
    }
}
----

When using Maven add the hibersap-ejb module to your application by defining the following dependency:

[source,xml,subs="+attributes"]
----
<dependency>
    <groupId>org.hibersap</groupId>
    <artifactId>hibersap-ejb</artifactId>
    <version>{hibersap-version}</version>
</dependency>
----



