
The main task of Hibersap is to map Remote Function Modules (RFMs) -- which are defined in SAP ERP -- to Java classes.
To accomplish this, Hibersap provides a set of Java annotations that map Java classes and their fields to the elements of the function module's interface.
This section provides detailed information on the Hibersap annotations and on how data types are converted.

For a complete example of how to define Hibersap classes and mappings, see the link:/getstarted[Hibersap Get Started Guide] or checkout the Hibersap examples code from GitHub.


=== Hibersap Annotations

Since Hibersap maps SAP Remote Function Modules to plain Java classes, an application must define one class for each function module that acts as a kind of proxy.
This class is called a BAPI class and has to be annotated with the `@Bapi` annotation.
(a http://en.wikipedia.org/wiki/Business_Application_Programming_Interface[BAPI], Business Application Programming Interface, is actually a subset of all Remote Function Modules in a SAP ERP system but provides a more handy term).
The annotation's `value` property defines the name of the corresponding function module:

[source,java]
----
@Bapi("BAPI_SFLIGHT_GETLIST")
public class FlightListBapi {
  ...
}
----

A function module's interface usually has a set of parameters which are either of a scalar data type (such as a number, a text or a date) or of a complex data type (in ABAP a complex type is called structure, and provides a set of attributes of scalar or complex data type).
In Hibersap, scalar parameters can be mapped directly to a field of the BAPI Java class, whereas structures are mapped to complex Java types, i.e. classes with a set of fields.
The classes representing an ABAP structure may be annotated with the @BapiStructure annotation, but this is not mandatory.
Since Structure class instances need to be created by Hibersap, they must have a default constructor.

[source,java]
----
@BapiStructure
public class BapiRet2 {
  ...
}
----

To map parameters of a function module to fields of Java classes, those fields have to be annotated with the `@Parameter` annotation.
Here, Hibersap needs to know the name of the function module's parameter as well as its type (scalar or complex) using the annotation's value and type properties respectively.
The Enumeration `ParameterType` defines the types `ParameterType.STRUCTURE` and `ParameterType.SIMPLE` for parameters of a complex or scalar type:

[source,java]
----
@Export
@Parameter(value = "RETURN", type = ParameterType.STRUCTURE)
private BapiRet2 returnData;
----

Since the interface parameters of ABAP functions are divided into import, export and table parameters, Hibersap has to know where to find the corresponding parameters.
The @Import, @Export and @Table annotations provide this information.

[source,java]
----
@BapiStructure
public class BapiRet2 {
    @Parameter("MESSAGE")
    private String message;
    ...
}
----

ABAP tables are lists of complex parameters. As such they are mapped to a Java array or a `java.util.Collection` field.
Hibersap again needs to know the name of the ABAP parameter as provided by the `@Parameter` annotation and its type as provided by the `@Table` annotation.
It is a special characteristic of table parameters in ABAP that they can be used as import parameters as well as export parameters.

Tables that import data to the function module are filled by the Java application, Hibersap will use the application-provided array or collection to populate the table.
Tables that export data from the function module will be read by Hibersap and copied to the corresponding array or collection.
Hibersap detects the type of its elements by the array type if it is declared as an array, or by its generic type if it is declared as a collection.
When using a collection, it is crucial to declare it with a generic type (the class Flight in the example), otherwise Hibersap will throw an error because it cannot determine the element type:

[source,java]
----
@Bapi("BAPI_SFLIGHT_GETLIST")
public class FlightListBapi {
    @Table
    @Parameter("FLIGHTLIST")
    private List<Flight> flightList;
}
----

The field representing a table does not need to be defined as a concrete implementation of the `java.util.Collection` interface.
When Hibersap creates a collection, it instantiates a `java.util.HashSet` for fields defined as `java.util.Set` and a `java.util.ArrayList` for fields defined as `java.util.Collection` or `java.util.List`.

The following list shows an overview of the Hibersap annotations.

[horizontal]
`*@Bapi*`::
    Maps a Java class to a Remote Function Module in SAP.
    `value`::: The name of the RFM, e.g. `BAPI_FLIGHT_GETLIST`

`*@BapiStructure*`::
    Maps the Java class to a structure in an RFM's interface.

`*@Parameter*`::
    Maps a field to a parameter of the RFM's interface.
    `value`::: The parameter's name as defined by the RFM.
    `type`::: The parameter's type, either `ParamType.SIMPLE` for a scalar type or `ParamType.STRUCTURE` for complex types. Default: `SIMPLE`.

`*@Import*`::
    Defines a field annotated with `@Parameter` to be an import parameter.

`*@Export*`::
    Defines a field annotated with `@Parameter` to be an export parameter.

`*@Table*`::
    Defines a field annotated with `@Parameter` to be a table parameter.

`*@Convert*`::
    The parameter's data type will be converted by the given converter, i.e. the Java field's data type may differ from the JCo data type conversion pattern.
    `converter`::: An implementation of `org.hibersap.conversion.Converter`.

`*@ThrowExceptionOnError*`::
	Tells Hibersap to throw a `org.hibersap.SapException` when the function module returns errors in a `RETURN` structure or table.
    `returnStructure`:::
      Contains the path to the BAPI's return structure or table, path elements are separated by a forward slash ('/'). The first element should be `EXPORT` or `TABLE` to indicate if the return structure is defined as an export or table parameter. The second element is the name of the return structure itself, usually `RETURN`. Default: "`EXPORT/RETURN`".
    `errorMessageTypes`:::
      The ABAP message types which Hibersap shall interpret as an error.
      The return structure's field `TYPE` is compared to the message types. Default: "E", "A".


=== Type Conversion


==== Default Conversion scheme

The Java type of each simple field is closely related to the ABAP field's data type.
When using Hibersap with JCo, it relies on the Java Connector's conversion scheme as shown in the following table.

[options="header"]
|===
| ABAP type | Description                | Java type
| C         | Character                  | java.lang.String
| N         | Numerical character        | java.lang.String
| D         | Date                       | java.lang.Date
| T         | Time                       | java.lang.Date
| X         | Byte field                 | byte[]
| P         | Packed number              | java.lang.BigDecimal
| I         | 4-byte integer             | int
| F         | Floating point number      | double
| STRING    | Variable-length character  | java.lang.String
| XSTRING   | Variable-length byte field | byte[]
|===


When using Hibersap with JCA, it relies on the data types returned by the Resource Adapter.
Most Resource Adapters for SAP use JCo, so the above type conversion scheme will apply here, too.


==== Custom Converters

Custom converters allow for converting a parameter's data type to any Java type and vice versa.
A common example for a custom converter is one that converts boolean values.
ABAP does not have a boolean data type, a boolean in ABAP is usually represented by a character field of length 1.
It evaluates to true if the parameter's value it equals to 'X', to false if the parameter's value is empty.
With a Hibersap converter it is possible to map an ABAP "boolean" parameter to a `boolean` field in Java.

You can use Hibersap converters to do any kind of data type conversion. There are a few Converters defined in package `org.hibersap.conversion`. However, it is easy to write your own converter by implementing the `org.hibersap.conversion.Converter` interface:

[source,java]
----
public interface Converter<J, S> extends Serializable
{
    /**
     * Convert the SAP value, as it is returned by the underlying
     * interfacing technology (e.g. the SAP Java Connector, JCo)
     * to the Java data type of the corresponding BAPI class field.
     * Hibersap will call this method after calling the SAP function
     * and before setting the field in the Java class.
     *
     * @param sapValue The object which is returned by the SAP interface
     * @return The converted value
     * @throws ConversionException if the value can not be converted
     */
    J convertToJava( S sapValue ) throws ConversionException;

    /**
     * Convert the Java value of the corresponding BAPI class field to
     * the data type as it is expected by the underlying interfacing
     * technology (e.g. the SAP Java Connector, JCo).
     * Hibersap will call this method before calling the SAP function.
     *
     * @param javaValue The value of the BAPI class field
     * @return The converted value
     * @throws ConversionException if the value can not be converted
     */
    S convertToSap( J javaValue ) throws ConversionException;
}
----

To use a converter, you simply annotate the field in the BAPI or Structure class with Hibersap's `@Convert` annotation, specifying the converter that should be called:

[source,java]
----
@Import
@Parameter ( "SHOW_DETAILS" )
@Convert( converter = BooleanConverter.class )
private final boolean showDetails;
----

You can use converters not only with simple parameters, but also with structure and table parameters. In case of a structure parameter, the object passed to `Converter.convertToJava()` will be a `java.util.Map` with the structure parameter names as keys and the parameter values as values. `Converter.convertToSap()` must return a Map like this.

When using a converter with a table parameter, the object passed to `Converter.convertToJava()` is a `java.util.List` with `java.util.Map` instances as list elements. Each of these maps has the structure parameter name as the map's key and the parameter's value as the map's value. `Converter.convertToSap()` must return a `List` of `Map`s of the same structure.


=== Bean Validation

Java Bean Validation (JSR 303) is a Java EE standard which defines an API and metadata model (in the form of Java annotations) to validate Java Beans and their attributes. If a Bean Validation provider is on the classpath of your application, Hibersap will validate the BAPI and Structure classes each time before a function gets executed.

To configure Bean Validation for your Hibersap application you may specify the validation element in the hibersap XML configuration file:

[source,xml]
----
<hibersap>
  <session-manager name="...">
    ...
    <validation-mode>AUTO</validation-mode>
    ...
  </session-manager>
</hibersap>
----

If using programmatic configuration, just set the `validationMode` property of the `SessionManagerConfig`:

[source,java]
----
sessionManagerConfig.setValidationMode( ValidationMode.AUTO );
----

The validation element may contain any of the values defined in `org.hibersap.configuration.xml.ValidationMode`:

[horizontal]
AUTO::     Use Bean Validation if a provider is found on the classpath (default).
CALLBACK:: Force the use of Bean Validation. Hibersap will throw an exception if no provider is found on the classpath.
NONE::     Do not use Bean Validation, even if a provider is present.
