name: Hibersap
title: Hibersap home
org: akquinet AG

interpolate: false
haml:
  :ugly: true

asciidoctor:
  :safe: safe
  :attributes:
    sitename: Hibersap
    base_url: ''
    ctx_path: ''
    idprefix: ''
    idseparator: '-'
    sectanchors: ''
    icons: font

profiles:
  production:
    base_url: http://hibersap.org
    deploy:
      host: github_pages
      branch: master
